# Generated by Django 3.0.2 on 2020-02-05 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='acquisition_date',
            field=models.DateField(auto_now=True),
        ),
    ]
