# Generated by Django 3.0.2 on 2020-03-05 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200227_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='acquisition_date',
            field=models.DateField(),
        ),
    ]
